# GitHub Secret Scanning Configuration
# https://docs.github.com/en/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning

# Paths to exclude from secret scanning (test files with dummy keys)
paths-ignore:
  - 'aiproxysrv/.env_test'
  - '**/*.test.js'
  - '**/*.spec.ts'
  - '**/test_*.py'
  - '**/conftest.py'
