---
# ═══════════════════════════════════════════════════════════
# Pipeline 1: Lint & Test (bei Push auf main)
# ═══════════════════════════════════════════════════════════
kind: pipeline
type: docker
name: lint-and-test

trigger:
  event:
    - push
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  - name: lint-frontend
    image: node:20-slim
    commands:
      - cd aiwebui
      - npm ci --prefer-offline --no-audit
      - npm run lint

---
# ═══════════════════════════════════════════════════════════
# Pipeline 2: Build & Deploy (nur bei Tags v*)
# ═══════════════════════════════════════════════════════════
kind: pipeline
type: docker
name: build-and-deploy

trigger:
  event:
    - tags
  ref:
    - refs/tags/v*
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  # ─────────────────────────────────────────────────────────
  # STEP 1: Version auslesen
  # ─────────────────────────────────────────────────────────
  - name: read-version
    image: alpine:latest
    commands:
      - echo "Reading VERSION files..."
      - cat aiproxysrv/VERSION || echo "v0.0.0" > aiproxysrv/VERSION
      - cat aiwebui/VERSION || echo "v0.0.0" > aiwebui/VERSION
      - export BACKEND_VERSION=$(cat aiproxysrv/VERSION | tr -d '[:space:]')
      - export FRONTEND_VERSION=$(cat aiwebui/VERSION | tr -d '[:space:]')
      - echo "Backend Version = $BACKEND_VERSION"
      - echo "Frontend Version = $FRONTEND_VERSION"
      - echo "Building for tag = ${DRONE_TAG}"

  # ─────────────────────────────────────────────────────────
  # STEP 2: Build aiproxysrv Docker Images
  # ─────────────────────────────────────────────────────────
  - name: build-aiproxysrv
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/rwellinger/aiproxysrv-app
      username: rwellinger
      password:
        from_secret: github_token
      context: aiproxysrv
      dockerfile: aiproxysrv/dockerfile
      target: app
      auto_tag: true
      auto_tag_suffix: ""
      tags:
        - latest
        - ${DRONE_TAG}

  # ─────────────────────────────────────────────────────────
  # STEP 3: Build celery-worker Docker Images
  # ─────────────────────────────────────────────────────────
  - name: build-celery-worker
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/rwellinger/celery-worker-app
      username: rwellinger
      password:
        from_secret: github_token
      context: aiproxysrv
      dockerfile: aiproxysrv/dockerfile
      target: worker
      auto_tag: true
      auto_tag_suffix: ""
      tags:
        - latest
        - ${DRONE_TAG}

  # ─────────────────────────────────────────────────────────
  # STEP 4: Build aiwebui Docker Image
  # ─────────────────────────────────────────────────────────
  - name: build-aiwebui
    image: plugins/docker
    settings:
      registry: ghcr.io
      repo: ghcr.io/rwellinger/aiwebui-app
      username: rwellinger
      password:
        from_secret: github_token
      context: aiwebui
      dockerfile: aiwebui/dockerfile
      target: production
      auto_tag: true
      auto_tag_suffix: ""
      tags:
        - latest
        - ${DRONE_TAG}
