---
# ═══════════════════════════════════════════════════════════
# Pipeline 1: Lint & Test (bei Push auf main)
# ═══════════════════════════════════════════════════════════
kind: pipeline
type: docker
name: lint-and-test

trigger:
  event:
  ref:
  branch:
    - main

platform:
  os: linux
  arch: arm64

steps:
  - name: lint-frontend
    image: node:20-slim
    commands:
      - cd aiwebui
      - npm ci --prefer-offline --no-audit
      - npm run lint
