"""add_artist_name_to_users

Revision ID: 75b410845228
Revises: d4641a241b98
Create Date: 2025-10-21 17:25:38.206689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b410845228'
down_revision: Union[str, Sequence[str], None] = 'd4641a241b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_sketches_created_at'), table_name='song_sketches')
    op.add_column('users', sa.Column('artist_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'artist_name')
    op.create_index(op.f('ix_song_sketches_created_at'), 'song_sketches', ['created_at'], unique=False)
    # ### end Alembic commands ###
